language: node_js
node_js:
  - "8"
sudo: required
services:
  - docker
after_deploy:
  - echo "done deploying"
  
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
  secure: "$SECRETACCESSKEY"
  region: "eu-west-3"
  app: "awstest"
  env: "awstest-dev"
  bucket_name: "https://s3.console.aws.amazon.com/s3/buckets/elasticbeanstalk-eu-west-3-161957065451?region=eu-west-3"
  on:
  branch: main

